site_name: "UCIMLR"

pages:
- Home: index.md
- Contributing: contrib.md
- API:
  - ucimlr.regression_datasets: regression_datasets.md
  - ucimlr.classification_datasets: classification_datasets.md

theme: readthedocs
